# Generated by Django 4.1.3 on 2022-12-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ahe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=50)),
                ("ahe", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Cpi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=50)),
                ("cpi", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Dxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=50)),
                ("close", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Fed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=50)),
                ("fed", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Jnk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=50)),
                ("close", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Pce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=50)),
                ("pce", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Ppi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=50)),
                ("ppi", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Rpceg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=50)),
                ("rpceg", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="TWII",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=50)),
                ("twii", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="UMCS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=50)),
                ("umcs", models.FloatField()),
            ],
        ),
    ]
